### PR TITLE
add check for TCM titlecard exif string

### PR DESCRIPTION
**Pull request by bullmoose20**

### CODE REVIEW

**Comment by chazlarson** [comment]
I think we probably want to be able to differentiate between the two cases, not lump them together.

**Comment by bullmoose20** [comment]
> I think I would want to be able to differentiate between the two cases, not lump them together.

So probably two separate helper functions? I guess this is what you meant?

**Comment by chazlarson** [comment]
Something so the code can differentiate between a PMM-modified image and this and any future third-party-modified image, since the next thing someone is going to want is to handle them differently.

**Comment by chazlarson** [comment]
Implemented somewhat differently.

**Pull request closed without merging**
